version: 2.1

executors:
  cypress_executor:
    docker:
      - image: cypress/base:10
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: cypress_executor
    steps:
      - checkout
      - run:
          name: Install Node.js Dependencies
          command: npm install

  run_cypress_tests:
    executor: cypress_executor
    steps:
      - checkout
      - run:
          name: Install Node.js Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_cypress_tests:
          requires:
            - install_dependencies
