version: 2.1

executors:
  cypress_executor:
    docker:
      - image: cypress/base:18.16.0  # Image dengan Node.js yang didukung
    working_directory: ~/project

jobs:
  install_dependencies:
    executor: cypress_executor
    steps:
      - checkout
      - run:
          name: Install Node.js (Ensure Correct Version)
          command: |
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install 18
            nvm use 18
            node -v
            npm -v
      - run:
          name: Install Dependencies
          command: npm install

  run_cypress_tests:
    executor: cypress_executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npx cypress run

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_cypress_tests:
          requires:
            - install_dependencies
