version: 2.1
orbs:
  cypress: cypress-io/cypress@3
workflows:
  build:
    jobs:
      - cypress/run:
          pre-steps:
            - run:
                name: Install dependencies
                command: npm install
            - run:
                name: Install Cypress
                command: npm install cypress --save-dev
          post-steps:
            - run:
                name: Run Cypress Tests
                command: npx cypress run
