version: 2.1
orbs:
  cypress: cypress-io/cypress@3

workflows:
  build:
    jobs:
      - cypress/run:
          pre-steps:
            - run:
                name: Clean working directory
                command: rm -rf ~/project/*
            - checkout
            - run:
                name: Install dependencies with Yarn
                command: yarn install
            - run:
                name: Install Cypress with Yarn
                command: yarn add cypress --dev
          post-steps:
            - run:
                name: Run Cypress Tests
                command: npx cypress run --headed
