name: Cypress CI

on:
  push:
    branches: [ master ] # Jalankan workflow pada push ke branch `master`
  pull_request:
    branches: [ master ] # Jalankan workflow pada setiap pull request ke branch `master`

jobs:
  build:
    name: Setup and Install Dependencies
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0 # Menggunakan Node.js versi 18.18.0

      # Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Install Cypress Binary
      - name: Install Cypress Binary
        run: npm install cypress --save-dev

  test:
    name: Run Cypress Tests
    needs: build # Jalankan setelah job `build` selesai
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3

      # Setup Node.js
      - name: Set up Node.js 18.18.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      # Run Cypress Tests
      - name: Run Cypress Tests
        run: npx cypress run
