jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install Dependencies
        run: npm install

  test:
    name: Test WEB
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0

      - name: Install Cypress
        run: npm install cypress --save-dev

      - name: Run Cypress Tests
        run: npx cypress run